config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /pt-BR|es|en/ do
    root :to => "home#index"
    get "home/index"
  end

  resources :comentarios
  resources :animais
  resources :plantas

  resources :experiencia_agroecologicas do
    resources :midias
    resources :comentarios
  end

  resources :safs do
    resources :midias
  end

  resources :tema_experiencia_agroecologicas

  resources :locais do
    resources :experiencia_agroecologicas
    resources :safs 
    resources :blogs, :path => "blog"
  end

  resources :organizacoes

  resources :tipo_organizacoes

  devise_for :usuarios

  resources :usuarios do
    resources :locais
  end

  resources :novidades, :only => [:index]
end

app/models/local.rb
class Local < ApplicationRecord
  belongs_to :usuario

  has_many :organizacao_locais, dependent: :nullify
  has_many :organizacoes, through: :organizacao_locais
  accepts_nested_attributes_for :organizacao_locais, allow_destroy: true

  has_many :safs, dependent: :destroy
  has_many :experiencia_agroecologicas, dependent: :destroy

  has_many :blogs, :dependent => :delete_all

  has_many :local_usuarios, dependent: :destroy
  has_many :usuarios, through: :local_usuarios
  accepts_nested_attributes_for :local_usuarios, allow_destroy: true

  extend FriendlyId
  friendly_id :nome, use: :slugged

  validates :nome, presence: true, uniqueness: true
  validates :tipo, presence: true

  has_attached_file :imagem, styles: { medium: "360x360>", thumb: "180x180>" }, default_url: "/assets/missing.png"
  validates_attachment_content_type :imagem, content_type: /\Aimage\/.*\z/

  protected
    def should_generate_new_friendly_id?
      nome_changed?
    end
end

app/controllers/locais_controller.rb
class LocaisController < ApplicationController
  before_action :set_local, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, only: [:new, :edit, :update, :destroy]
  before_action -> { check_owner Local.friendly.find(params[:id]).usuario_id }, only: [:edit, :update, :destroy]
  before_action :load_tipos, except: [:index, :show]
  before_action :load_hospedagens, except: [:index, :show]
  before_action :load_usuario
  before_action :load_colaboradores, only: [:new, :edit, :update]

  # GET /locais
  # GET /locais.json
  def index
    if params[:usuario_id]
      @locais = Local.where(:usuario_id => @usuario.id).sort_by(&:updated_at).reverse
    else
      @locais = Local.all.sort_by(&:updated_at).reverse
    end
  end

  # GET /locais/1
  # GET /locais/1.json
  def show
  end

  # GET /locais/new
  def new
    @local = Local.new
    @local.local_usuarios.build
  end

  # GET /locais/1/edit
  def edit
    @local.local_usuarios.build
  end

  # POST /locais
  # POST /locais.json
  def create
    @local = Local.new(local_params)

    if ! current_usuario.admin?
      @local.usuario_id = current_usuario.id
    end

    respond_to do |format|
      if @local.save
        format.html { redirect_to @local, notice: 'Local foi cadastrado.' }
        format.json { render :show, status: :created, location: @local }
      else
        format.html { render :new }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locais/1
  # PATCH/PUT /locais/1.json
  def update
    respond_to do |format|
      if @local.update(local_params)
        format.html { redirect_to @local, notice: 'Local foi atualizado.' }
        format.json { render :show, status: :ok, location: @local }
      else
        format.html { render :edit }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locais/1
  # DELETE /locais/1.json
  def destroy
    @local.destroy
    respond_to do |format|
      format.html { redirect_to locais_url, notice: 'Local foi removido.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local
      @local = Local.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def local_params
      params.require(:local).permit(:nome, :slug, :observacao, :latitude, :longitude, :usuario_id, :imagem, :tipo, :hospedagem, :usuario_ids => [])
    end

    def load_tipos
      @tipos = { "Assentamento" => "Assentamento",
                 "Propriedade Coletiva" => "Propriedade Coletiva",
                 "Propriedade Pública (Governo)" => "Propriedade Pública (Governo)",
                 "Propriedade Privada" => "Propriedade Privada",
                 "Familiar" => "Familiar",
                 "Outro" => "Outro"
               }
    end

    def load_hospedagens
      @hospedagens = { "Mediante a Consulta" => "Mediante a Consulta",
                       "Sim" => "Sim",
                       "Não" => "Não"
                     }
    end

    def load_colaboradores
      @usuarios = Usuario.all
    end

    def load_usuario
      if params[:usuario_id]
        @usuario = Usuario.friendly.find(params[:usuario_id])
      end
    end
end

app/views/locais/_form.html.erb
<%= form_for(local, html: { multipart: true }) do |f| %>
  <% if local.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(local.errors.count, "error") %> encontrado(s):</h2>

      <ul>
      <% local.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_usuario.admin? %>
    <div class="form-group row">
      <%= f.label 'Responsável', class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <%= f.collection_select(:usuario_id, Usuario.all, :id, :nome,  {}, { class: "form-control selectpicker", "data-live-search": true } ) %>
      </div>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label 'Colaboradores Parceiros', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <% if ! @usuarios.empty? %>
        <%= f.collection_select(:usuario_ids, @usuarios, :id, :nome,  { include_hidden: true }, { class: "form-control selectpicker show-tick", multiple: true, "data-live-search": true } ) %>
      <% else %>
        <b>Não há Colaboradores Registrados. Deseja <%= link_to "Cadastrar?", new_usuario_path, :target => "blank"%></b>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Nome', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Tipo', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.collection_select(:tipo, @tipos, :last, :first,  { :include_blank => 'Selecione um Tipo de Local' }, { class: "form-control selectpicker", "data-live-search": true } ) %>
    </div>
  </div>


  <div class="form-group row">
    <%= f.label "Imagem", class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-8">
      <%= f.file_field :imagem, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Observação', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.text_area :observacao, class: "form-control", :rows => "5"  %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Hospedagem', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.collection_select(:hospedagem, @hospedagens, :last, :first,  { :include_blank => 'Aceita Hospedar Pessoa/Grupo?' }, { class: "form-control selectpicker", "data-live-search": true } ) %>
    </div>
  </div>

  <div class="col-form-label-lg">Localização (<span class="text-danger">Use a Lupa para Buscar o Local e Clique para Marcar</span>)</div>
  <div class="form-group row">
      <div id="map-sistema"></div>
  </div>
  <br/><br/>

  <%= f.hidden_field :latitude, id: "latitude" %>
  <%= f.hidden_field :longitude, id: "longitude" %>

  <br/>

  <div class="actions">
    <%= f.submit t(:submit), class: "btn btn-primary" %>
  </div>

  <script>
    $( document ).ready(function() {
      lat = <%= (defined? request.safe_location.latitude)  ? request.safe_location.latitude : 0.0 %>;
      lon = <%= (defined? request.safe_location.longitude) ? request.safe_location.longitude : 0.0 %>;

      <% if params[:action] == 'new' %>
        if (lat == 0.0 || lon == 0.0) {
          lat = -15.77835833463309;
          lon = -47.88219451904297;
        }
      <% else %>
          lat = <%= f.object.latitude %>;
          lon = <%= f.object.longitude %>;
      <% end %>

      var map = L.map('map-sistema', {zoomControl: false}).setView([lat, lon], 10);

      $(window).on("resize", function () { $("#map-sistema").width($(window).width()); map.invalidateSize(); }).trigger("resize");
      $(window).on("resize", function () { $("#map-sistema").height($(window).height()); map.invalidateSize(); }).trigger("resize");

      var osm    = L.tileLayer('https://a.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '<a href="https://itbio3.org">ITBio3</a> | Agroecologia | OpenStreetMap', maxZoom: 18,}).addTo(map);
      var mapbox = L.tileLayer('https://api.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFyY2Vsb3NvYXJlc3NvdXphIiwiYSI6ImNpZ2NpNXFmMzNvaDh3Ym0zeXM3aWN3Y2EifQ.1xOQgKK1MioUioN0B4DVog', { attribution: '<a href="https://itbio3.org">ITBio3</a> | Mapa da Agroecologia | MapBox', maxZoom: 18,});
      var baseMaps = { "OpenStreetMap": osm, "Satélite (MapBox)": mapbox };

      L.control.layers(baseMaps).addTo(map);

      L.control.zoom({position:'topright'}).addTo(map);

      var osmGeocoder = new L.Control.OSMGeocoder({placeholder: 'Informe a Cidade/Estado/País'});
      map.addControl(osmGeocoder);

      var Icon = L.icon({
                            iconUrl: '<%= image_url "leaflet/images/leaf-green.png" %>',
                            shadowUrl: '<%= image_url "leaflet/images/leaf-shadow.png" %>',
                            iconSize:     [38, 95],
                            shadowSize:   [50, 64],
                            iconAnchor:   [22, 94],
                            shadowAnchor: [4, 62],
                            popupAnchor:  [-3, -76]
                        });

      var marker = L.marker(new L.LatLng(lat, lon), { draggable: true, icon: Icon }).addTo(map);

      $('#latitude').val(lat);
      $('#longitude').val(lon);

      map.on('click', function (e) {
        marker.setLatLng(e.latlng);
        $('#latitude').val(marker.getLatLng().lat);
        $('#longitude').val(marker.getLatLng().lng);
      });

      marker.on('dragend', function (e) {
        $('#latitude').val(marker.getLatLng().lat);
        $('#longitude').val(marker.getLatLng().lng);
      });
    });
  </script>
<% end %>

app/views/locais/edit.html.erb
<% title "Editando #{@local.nome}" %>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "Locais", locais_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{t(:edit)} #{@local.nome}", edit_local_path(@local), :class => "nav-link active" %>
  </li>
</ul>
<br/>
<%= render 'form', local: @local %>

app/views/locais/index.html.erb
<% title 'Locais' %>

<%= link_to I18n.t("location.register_new_location"), new_local_path, :class => "btn btn-primary", :style => "float:right;" %>
<br/><br/><br/>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "Locais #{ @usuario.blank? ? '' : '(' + @usuario.nome + ')' }", "#", :class => "nav-link active" %>
  </li>
</ul>

<% if @locais.empty? %>
  <br/>
  <h3>Nenhum Local Registrado</h3>
<% else %>

  <br/>
  <div style="overflow-x:auto;">
    <table id="dataTable-agroecologia" class="table table-striped table-bordered" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th></th>
          <th>Nome do Local</th>
          <th>Tipo</th>
          <th>Experiências</th>
          <th>SAFs</th>
          <th>Blog</th>
          <% if usuario_signed_in? %><th class="list-control"></th><th class="list-control"></th><% end %>
        </tr>
      </thead>

      <tbody>
        <% @locais.each do |local| %>
        <tr>
          <td scope="row"><%= link_to image_tag(local.imagem.url(:thumb), :width => "120", :height => "120"), local_path(local) %></td>
          <td><%= link_to truncate(local.nome, length: 128), local_path(local) %></td>
          <td><%= local.tipo %></td>
          <td><%= link_to local.experiencia_agroecologicas.count, local_experiencia_agroecologicas_path(local) %></td>
          <td><%= link_to local.safs.count, local_safs_path(local) %></td>
          <td><%= link_to local.blogs.count, local_blogs_path(local) %></td>

          <% if usuario_signed_in? %>
            <% if current_usuario.admin? or local.usuario.id == current_usuario.id %>
              <td><%= link_to t(:edit), edit_local_path(local), :class => 'btn btn-sm btn-success' %></td>
              <td><%= link_to t(:destroy), local_path(local), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-sm btn-danger' %></td>
            <% else %>
              <td></td><td></td>
            <% end %>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <script>$(document).ready(function(){ dataTables(); });</script>
<% end %>

app/views/locais/new.html.erb
<% title 'Adicionar Local' %>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "Locais", locais_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:new), new_local_path, :class => "nav-link active" %>
  </li>
</ul>

<br/>

<%= render 'form', local: @local %>

app/views/locais/show.html.erb
<% title @local.nome %>

<%= link_to "Registrar Novo Local", new_local_path, :class => "btn btn-primary", :style => "float:right;" %>
<br/><br/><br/>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "Locais", locais_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to @local.nome, local_path(@local.id), :class => "nav-link active" %>
  </li>

  <li class="nav-item">
    <%= link_to "Blog (#{@local.blogs.count})", local_blogs_path(@local), :class => "nav-link" %>
  </li>
</ul>

<br/>

<div class="tab-content" style="min-height: 64px;">
  <div class="tab-pane active">
    <center>
      <%= image_tag(@local.imagem.url(:medium), :width => "250") %>

      <br/><br/>
      <h3><%= @local.nome %></h3>

      <br/>
      <%= "<strong>Tipo:</strong><br/>#{@local.tipo}&nbsp;".html_safe if @local.tipo? %>
      <%= "<br/><br/><strong>Responsável pela Informação:</strong><br/>#{link_to @local.usuario.nome, usuario_path(@local.usuario)}&nbsp;".html_safe if @local.usuario.nome?%>
      <%= "<br/><br/><strong>Colaboradores:</strong><br/>#{@local.usuarios.map {|usuario| link_to usuario.nome, usuario_path(usuario)}.join(", ").html_safe}&nbsp;".html_safe if @local.usuarios.count > 0%>
      <%= "<br/><br/><strong>Aceita Hospedar Pessoa/Grupo:</strong><br/>#{@local.hospedagem}&nbsp;".html_safe if @local.hospedagem? %>
      <%= "<br/><br/><strong>Observação:</strong><br/>#{@local.observacao}&nbsp;".html_safe if @local.observacao?%>
      <%= "<br/><br/><strong>Organizações:</strong><br/>#{@local.organizacoes.map {|organizacao| link_to organizacao.nome, organizacao_path(organizacao)}.join(", ").html_safe}&nbsp;".html_safe if @local.organizacoes.count > 0%>
      <%= "<br/><br/><strong>Experiências em Agroecologia:</strong><br/>#{@local.experiencia_agroecologicas.map {|experiencia_agroecologica| link_to experiencia_agroecologica.nome, experiencia_agroecologica_path(experiencia_agroecologica)}.join(", ").html_safe}&nbsp;".html_safe if @local.experiencia_agroecologicas.count > 0%>
      <%= "<br/><br/><strong>SAFs:</strong><br/>#{@local.safs.map {|saf| link_to saf.nome, saf_path(saf)}.join(", ").html_safe}&nbsp;".html_safe if @local.safs.count > 0%>
      <%= "<br/><br/><strong>Últimas do Blog:</strong><br/>#{@local.blogs.order(updated_at: :desc).take(10).map {|blog| link_to blog.titulo, local_blog_url(@local, blog)}.join("<br/>").html_safe}&nbsp;".html_safe if @local.blogs.count > 0%>

      <% if @local.latitude and @local.longitude %>
        <br/><br/>
        <strong>Localização:</strong><br/>
        <div class="form-group row"><div id="map"></div></div>

        <script>
        $( document ).ready(function() {
          var map = L.map('map').setView([<%= @local.latitude %>, <%= @local.longitude %>], 10);

          var osm    = L.tileLayer('https://a.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '<a href="https://itbio3.org">ITBio3</a> | Agroecologia | OpenStreetMap', maxZoom: 18,}).addTo(map);
          var mapbox = L.tileLayer('https://api.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFyY2Vsb3NvYXJlc3NvdXphIiwiYSI6ImNpZ2NpNXFmMzNvaDh3Ym0zeXM3aWN3Y2EifQ.1xOQgKK1MioUioN0B4DVog', { attribution: '<a href="https://itbio3.org">ITBio3</a> | Mapa da Agroecologia | MapBox', maxZoom: 18,});
          var baseMaps = { "OpenStreetMap": osm, "Satélite (MapBox)": mapbox };

          L.control.layers(baseMaps).addTo(map);

          var Icon = L.icon({
                            iconUrl: '<%= image_url "leaflet/images/leaf-green.png" %>',
                            shadowUrl: '<%= image_url "leaflet/images/leaf-shadow.png" %>',
                            iconSize:     [38, 95],
                            shadowSize:   [50, 64],
                            iconAnchor:   [22, 94],
                            shadowAnchor: [4, 62],
                            popupAnchor:  [-3, -76]
                          });
          $(window).on("resize", function () { $("#map").width($(window).width() - 30); map.invalidateSize(); }).trigger("resize");
          $(window).on("resize", function () { $("#map").height($(window).height()); map.invalidateSize(); }).trigger("resize");

          L.marker([<%= @local.latitude %>, <%= @local.longitude %>], {icon: Icon}).addTo(map);
        });
        </script>
    <% end %>
    </center>
    </div>
</div>

<% if usuario_signed_in? %>
  <% if current_usuario.admin? or current_usuario.id == @local.usuario.id %>        
    <br/><br/>
    <div class="form-actions">
      <%= link_to t('.edit', :default => "Editar"), edit_local_path(@local), :class => 'btn btn-success' %>
      <%= link_to "Registrar Experiência neste Local", new_local_experiencia_agroecologica_path(@local), :class => "btn btn-info" %>
      <%= link_to "Registrar SAF neste Local", new_local_saf_path(@local), :class => "btn btn-warning" %>

      <%= link_to t(:destroy), local_path(@local), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-danger' %>
    </div>
  <% end %>
<% end %>