config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /pt-BR|es|en/ do
    root :to => "home#index"
    get "home/index"
  end

  resources :comentarios
  resources :animais
  resources :plantas

  resources :experiencia_agroecologicas do
    resources :midias
    resources :comentarios
  end

  resources :safs do
    resources :midias
  end

  resources :tema_experiencia_agroecologicas

  resources :locais do
    resources :experiencia_agroecologicas
    resources :safs 
    resources :blogs, :path => "blog"
  end

  resources :organizacoes

  resources :tipo_organizacoes

  devise_for :usuarios

  resources :usuarios do
    resources :locais
  end

  resources :novidades, :only => [:index]
end

app/models/midia.rb
class Midia < ApplicationRecord
  belongs_to :saf, required: false
  belongs_to :experiencia_agroecologica, required: false

  extend FriendlyId
  friendly_id :descricao, use: :slugged

  validates :descricao, presence: true, uniqueness: true
  validates :imagem, presence: true

  has_attached_file :imagem, styles: { medium: "360x360>", thumb: "180x180>" }, default_url: "/assets/missing.png"
  validates_attachment_content_type :imagem, content_type: /\Aimage\/.*\z/

  protected
    def should_generate_new_friendly_id?
      descricao_changed?
    end
end

app/controllers/midias_controller.rb
class MidiasController < ApplicationController
  before_action :set_midia, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, only: [:new, :edit, :update, :destroy]
  before_action -> { check_owner Midia.friendly.find(params[:id]).usuario_id }, only: [:edit, :update, :destroy]
  before_action :load_dados

  # GET /midias
  # GET /midias.json
  def index
    if params[:saf_id]
      @midias = Midia.where(:saf_id => @saf.id)
    elsif params[:experiencia_agroecologica_id]
      @midias = Midia.where(:experiencia_agroecologica_id => @experiencia_agroecologica.id)
    end
  end

  # GET /midias/1
  # GET /midias/1.json
  def show
  end

  # GET /midias/new
  def new
    @midia = Midia.new
  end

  # GET /midias/1/edit
  def edit
  end

  # POST /midias
  # POST /midias.json
  def create
    @midia = Midia.new(midia_params)

    if ! current_usuario.admin?
      @midia.usuario_id = current_usuario.id
    end

    if params[:saf_id]
      @midia.saf_id = @saf.id
    elsif params[:experiencia_agroecologica_id]
      @midia.experiencia_agroecologica_id = @experiencia_agroecologica.id
    end

    respond_to do |format|
      if @midia.save
        if params[:saf_id]
          format.html { redirect_to saf_midia_path(@saf, @midia), notice: 'Midia foi cadastrada.' }
        elsif params[:experiencia_agroecologica_id]
          format.html { redirect_to experiencia_agroecologica_midia_path(@experiencia_agroecologica, @midia), notice: 'Midia foi cadastrada.' }
        end
        format.json { render :show, status: :created, location: @midia }
      else
        format.html { render :new }
        format.json { render json: @midia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /midias/1
  # PATCH/PUT /midias/1.json
  def update
    respond_to do |format|
      if @midia.update(midia_params)
        if params[:saf_id]
          format.html { redirect_to saf_midia_path(@saf, @midia), notice: 'Midia foi atualizada.' }
        elsif params[:experiencia_agroecologica_id]
          format.html { redirect_to experiencia_agroecologica_midia_path(@experiencia_agroecologica, @midia), notice: 'Midia foi atualizada' }
        end
        format.json { render :show, status: :ok, location: @midia }
      else
        format.html { render :edit }
        format.json { render json: @midia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /midias/1
  # DELETE /midias/1.json
  def destroy
    @midia.destroy

    respond_to do |format|
      if params[:saf_id]
        format.html { redirect_to saf_midias_path(@saf), notice: 'Midia foi removida.' }
      elsif params[:experiencia_agroecologica_id]
        format.html { redirect_to experiencia_agroecologica_midias_path(@experiencia_agroecologica), notice: 'Midia foi removida.' }
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_midia
      @midia = Midia.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def midia_params
      params.require(:midia).permit(:descricao, :slug, :saf_id, :experiencia_agroecologica_id, :imagem, :usuario_id)
    end

    def load_dados
      if params[:saf_id]
        @saf = Saf.friendly.find(params[:saf_id])
      elsif params[:experiencia_agroecologica_id]
        @experiencia_agroecologica = ExperienciaAgroecologica.friendly.find(params[:experiencia_agroecologica_id])
      end
    end
end

app/views/midias/_form.html.erb
<%= form_for_midia @saf do |f| %>
  <% if midia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(midia.errors.count, "error") %> encontrado(s):</h2>

      <ul>
      <% midia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_usuario.admin? %>
    <div class="form-group row">
      <%= f.label 'Colaborador Responsável', class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <%= f.collection_select(:usuario_id, Usuario.all, :id, :nome,  {}, { class: "form-control selectpicker", "data-live-search": true } ) %>
      </div>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label 'Descrição', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.text_field :descricao, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label "Imagem", class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-8">
      <%= f.file_field :imagem, class: "form-control" %>
    </div>
  </div>

  <br/>

  <div class="actions">
    <%= f.submit t(:submit), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/midias/edit.html.erb
<% title "Editando Foto #{@midia.descricao}" %>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <% if params[:saf_id] %>
      <%= link_to "SAFs", safs_path, :class => "nav-link" %>
    <% elsif params[:experiencia_agroecologica_id] %>
      <%= link_to "Experiências em Agroecologia", experiencia_agroecologicas_path, :class => "nav-link" %>
    <% end %>
   </li>

  <li class="nav-item">
    <% if params[:saf_id] %>
      <%= link_to @saf.nome, saf_path(@saf), :class => "nav-link" %>
    <% elsif params[:experiencia_agroecologica_id] %>
      <%= link_to @experiencia_agroecologica.nome, experiencia_agroecologica_path(@experiencia_agroecologica), :class => "nav-link" %>
    <% end %>
   </li>

  <li class="nav-item">
    <% if params[:saf_id] %>
      <%= link_to "Fotos (#{@saf.midias.count})", saf_midias_path, :class => "nav-link" %>
    <% elsif params[:experiencia_agroecologica_id] %>
      <%= link_to "Fotos (#{@experiencia_agroecologica.midias.count})", experiencia_agroecologica_midias_path, :class => "nav-link" %>
    <% end %>
  </li>

  <li class="nav-item">
    <% if params[:saf_id] %>
      <%= link_to "#{t(:edit)} #{@midia.descricao}", edit_saf_midia_path, :class => "nav-link active" %>
    <% elsif params[:experiencia_agroecologica_id] %>
      <%= link_to "#{t(:edit)} #{@midia.descricao}", edit_experiencia_agroecologica_midia_path, :class => "nav-link active" %>
    <% end %>
  </li>
</ul>

<br/>

<%= render 'form', midia: @midia %>

app/views/midias/index.html.erb
<% if params[:saf_id] %>
  <% title "Fotos #{@saf.nome}" %>
<% elsif params[:experiencia_agroecologica_id] %>
  <% title "Fotos #{@experiencia_agroecologica.nome}" %>
<% end %>

<% if usuario_signed_in? %>
  <% if params[:saf_id] %>
    <%= link_to "Enviar Foto para esta SAF", new_saf_midia_path, :class => "btn btn-warning", :style => "float:right;"  if current_usuario.admin? or @saf.usuario_id == current_usuario.id %>
  <% elsif params[:experiencia_agroecologica_id] %>
    <%= link_to "Enviar Foto para esta Experiência", new_experiencia_agroecologica_midia_path, :class => "btn btn-warning", :style => "float:right;" if current_usuario.admin? or @experiencia_agroecologica.usuario_id == current_usuario.id %>
  <% end %>
<% end %>

<br/><br/><br/>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <% if params[:saf_id] %>
      <%= link_to "SAFs", safs_path, :class => "nav-link" %>
    <% elsif params[:experiencia_agroecologica_id] %>
      <%= link_to "Experiências em Agroecologia", experiencia_agroecologicas_path, :class => "nav-link" %>
    <% end %>
   </li>

  <li class="nav-item">
    <% if params[:saf_id] %>
      <%= link_to @saf.nome, saf_path(@saf), :class => "nav-link" %>
    <% elsif params[:experiencia_agroecologica_id] %>
      <%= link_to @experiencia_agroecologica.nome, experiencia_agroecologica_path(@experiencia_agroecologica), :class => "nav-link" %>
    <% end %>
   </li>

  <li class="nav-item">
    <% if params[:saf_id] %>
      <%= link_to "Fotos (#{@saf.midias.count})", saf_midias_path, :class => "nav-link active" %>
    <% elsif params[:experiencia_agroecologica_id] %>
      <%= link_to "Fotos (#{@experiencia_agroecologica.midias.count})", experiencia_agroecologica_midias_path, :class => "nav-link active" %>
    <% end %>
  </li>
</ul>

<% if @midias.empty? %>
  <br/>

  <h3>Nenhuma Foto Registrada.
   <% if usuario_signed_in? %>
      <% if params[:saf_id] %>
        <%= link_to "Enviar uma Foto para esta SAF?", new_saf_midia_path(@saf) if current_usuario.admin? or @saf.usuario_id == current_usuario.id %>
      <% elsif params[:experiencia_agroecologica_id] %>
        <%= link_to "Enviar uma Foto para esta Experiência?", new_experiencia_agroecologica_midia_path(@experiencia_agroecologica) if current_usuario.admin? or @experiencia_agroecologica.usuario_id == current_usuario.id %>
      <% end %>
    <% end %>
  </h3>

<% else %>

  <br/>
  <div style="overflow-x:auto;">
    <table id="dataTable-agroecologia" class="table table-striped table-bordered" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th></th>
          <th>Descrição</th>
          <% if usuario_signed_in? %>
            <th class="list-control"></th>
            <th class="list-control"></th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @midias.each do |midia| %>
        <tr>
          <% if params[:saf_id] %>
            <td scope="row"><%= link_to image_tag(midia.imagem.url(:thumb), :height => "80"), saf_midia_path(@saf, midia) %></td>
            <td><%= link_to midia.descricao, saf_midia_path(@saf, midia) %></td>
          <% elsif params[:experiencia_agroecologica_id] %>
            <td scope="row"><%= link_to image_tag(midia.imagem.url(:thumb), :height => "80"), experiencia_agroecologica_midia_path(@experiencia_agroecologica, midia) %></td>
            <td><%= link_to midia.descricao, experiencia_agroecologica_midia_path(@experiencia_agroecologica, midia) %></td>
          <% end %>

          <% if usuario_signed_in? %>
            <% if current_usuario.admin? or midia.usuario_id == current_usuario.id %>
              <% if params[:saf_id] %>
                <td><%= link_to t(:edit), edit_saf_midia_path(@saf, midia), :class => 'btn btn-sm btn-success' %></td>
                <td><%= link_to t(:destroy), saf_midia_path(@saf, midia), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-sm btn-danger' %></td>
              <% elsif params[:experiencia_agroecologica_id] %>
                <td><%= link_to t(:edit), edit_experiencia_agroecologica_midia_path(@experiencia_agroecologica, midia), :class => 'btn btn-sm btn-success' %></td>
                <td><%= link_to t(:destroy), experiencia_agroecologica_midia_path(@experiencia_agroecologica, midia), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-sm btn-danger' %></td>
              <% end %>
            <% else %>
              <td></td>
              <td></td>
            <% end %>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <script>$(document).ready(function(){ dataTables(); });</script>
<% end %>

app/views/midias/new.html.erb
<% if params[:saf_id] %>
  <% title "Adicionar Foto em #{@saf.nome}" %>
<% elsif params[:experiencia_agroecologica_id] %>
  <% title "Adicionar Foto em #{@experiencia_agroecologica.nome}" %>
<% end %>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <% if params[:saf_id] %>
      <%= link_to "SAFs", safs_path, :class => "nav-link" %>
    <% elsif params[:experiencia_agroecologica_id] %>
      <%= link_to "Experiências em Agroecologia", experiencia_agroecologicas_path, :class => "nav-link" %>
    <% end %>
   </li>

  <li class="nav-item">
    <% if params[:saf_id] %>
      <%= link_to @saf.nome, saf_path(@saf), :class => "nav-link" %>
    <% elsif params[:experiencia_agroecologica_id] %>
      <%= link_to @experiencia_agroecologica.nome, experiencia_agroecologica_path(@experiencia_agroecologica), :class => "nav-link" %>
    <% end %>
   </li>

  <li class="nav-item">
    <% if params[:saf_id] %>
      <%= link_to "Fotos (#{@saf.midias.count})", saf_midias_path, :class => "nav-link" %>
    <% elsif params[:experiencia_agroecologica_id] %>
      <%= link_to "Fotos (#{@experiencia_agroecologica.midias.count})", experiencia_agroecologica_midias_path, :class => "nav-link" %>
    <% end %>
  </li>

  <% if usuario_signed_in? %>
    <li class="nav-item">
      <% if params[:saf_id] %>
        <%= link_to "Enviar Foto para esta SAF", new_saf_midia_path, :class => "nav-link active" %>
      <% elsif params[:experiencia_agroecologica_id] %>
        <%= link_to "Enviar Foto para esta Experiência", new_experiencia_agroecologica_midia_path, :class => "nav-link active" %>
      <% end %>
    </li>
  <% end %>
</ul>

<br/>

<%= render 'form', midia: @midia %>

app/views/midias/show.html.erb
<% if params[:saf_id] %>
  <% title "#{@midia.descricao} | #{@saf.nome}" %>
<% elsif params[:experiencia_agroecologica_id] %>
  <% title "#{@midia.descricao} | #{@experiencia_agroecologica.nome}" %>
<% end %>

<% if usuario_signed_in? %>
  <% if params[:saf_id] %>
    <%= link_to "Enviar Foto para esta SAF", new_saf_midia_path, :class => "btn btn-warning", :style => "float:right;"  if current_usuario.admin? or @saf.usuario_id == current_usuario.id %>
  <% elsif params[:experiencia_agroecologica_id] %>
    <%= link_to "Enviar Foto para esta Experiência", new_experiencia_agroecologica_midia_path, :class => "btn btn-warning", :style => "float:right;" if current_usuario.admin? or @experiencia_agroecologica.usuario_id == current_usuario.id %>
  <% end %>
<% end %>

<br/><br/><br/>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <% if params[:saf_id] %>
      <%= link_to "SAFs", safs_path, :class => "nav-link" %>
    <% elsif params[:experiencia_agroecologica_id] %>
      <%= link_to "Experiências em Agroecologia", experiencia_agroecologicas_path, :class => "nav-link" %>
    <% end %>
   </li>

  <li class="nav-item">
    <% if params[:saf_id] %>
      <%= link_to @saf.nome, saf_path(@saf), :class => "nav-link" %>
    <% elsif params[:experiencia_agroecologica_id] %>
      <%= link_to @experiencia_agroecologica.nome, experiencia_agroecologica_path(@experiencia_agroecologica), :class => "nav-link" %>
    <% end %>
   </li>

  <li class="nav-item">
    <% if params[:saf_id] %>
      <%= link_to "Fotos (#{@saf.midias.count})", saf_midias_path, :class => "nav-link" %>
    <% elsif params[:experiencia_agroecologica_id] %>
      <%= link_to "Fotos (#{@experiencia_agroecologica.midias.count})", experiencia_agroecologica_midias_path, :class => "nav-link" %>
    <% end %>
  </li>

  <li class="nav-item">
    <% if params[:saf_id] %>
      <%= link_to @midia.descricao, saf_midia_path(@saf, @midia.id), :class => "nav-link active" %>
    <% elsif params[:experiencia_agroecologica_id] %>
      <%= link_to @midia.descricao, experiencia_agroecologica_midia_path(@experiencia_agroecologica, @midia.id), :class => "nav-link active" %>
    <% end %>
  </li>
</ul>



<br/>

<div class="tab-content" style="min-height: 64px;">
  <div class="tab-pane active">
    <center>
      <%= image_tag(@midia.imagem.url, :class => "midia-imagem") %>

      <br/><br/>
      <h3><%= @midia.descricao %></h3>
    </center>
    </div>
</div>

<% if usuario_signed_in? %>
  <% if current_usuario.admin? or current_usuario.id == @midia.usuario_id %>        
    <br/><br/>
    <div class="form-actions">
      <% if params[:saf_id] %>
        <%= link_to t(:edit), edit_saf_midia_path(@saf, @midia), :class => 'btn btn-mini btn-success' %>
      <%= link_to t(:destroy), saf_midia_path(@saf, @midia), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-mini btn-danger' %>
      <% elsif params[:experiencia_agroecologica_id] %>
        <%= link_to t(:edit), edit_experiencia_agroecologica_midia_path(@experiencia_agroecologica, @midia), :class => 'btn btn-mini btn-success' %>
        <%= link_to t(:destroy), experiencia_agroecologica_midia_path(@experiencia_agroecologica, @midia), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-mini btn-danger' %>
      <% end %>
    </div>
  <% end %>
<% end %>