config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /pt-BR|es|en/ do
    root :to => "home#index"
    get "home/index"
  end

  resources :comentarios
  resources :animais
  resources :plantas

  resources :experiencia_agroecologicas do
    resources :midias
    resources :comentarios
  end

  resources :safs do
    resources :midias
  end

  resources :tema_experiencia_agroecologicas

  resources :locais do
    resources :experiencia_agroecologicas
    resources :safs 
    resources :blogs, :path => "blog"
  end

  resources :organizacoes

  resources :tipo_organizacoes

  devise_for :usuarios

  resources :usuarios do
    resources :locais
  end

  resources :novidades, :only => [:index]
end

app/models/experiencia_agroecologica.rb
class ExperienciaAgroecologica < ApplicationRecord
  belongs_to :usuario
  belongs_to :local
  belongs_to :tema_experiencia_agroecologica
  has_one :organizacao, through: :local
  has_many :midias, :dependent => :delete_all
  has_many :comentarios

  extend FriendlyId
  friendly_id :nome, use: :slugged

  validates :nome, presence: true, uniqueness: true
  validates :local, presence: true
  validates :tema_experiencia_agroecologica, presence: true

  protected
    def should_generate_new_friendly_id?
      nome_changed?
    end
end

app/controllers/experiencia_agroecologicas_controller.rb
class ExperienciaAgroecologicasController < ApplicationController
  before_action :set_experiencia_agroecologica, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, only: [:new, :edit, :update, :destroy]
  before_action -> { check_owner ExperienciaAgroecologica.friendly.find(params[:id]).usuario_id }, only: [:edit, :update, :destroy]
  before_action :load_locais, except: [:index, :show]
  before_action :load_tema_experiencia_agroecologicas, except: [:index, :show]
  before_action :load_local

  # GET /experiencia_agroecologicas
  # GET /experiencia_agroecologicas.json
  def index
    if params[:local_id]
      @experiencia_agroecologicas = ExperienciaAgroecologica.where(:local_id => @local.id).sort_by(&:updated_at).reverse
    else
      @experiencia_agroecologicas = ExperienciaAgroecologica.all.sort_by(&:updated_at).reverse
    end
  end

  # GET /experiencia_agroecologicas/1
  # GET /experiencia_agroecologicas/1.json
  def show
    @comentar = Comentario.new
  end

  # GET /experiencia_agroecologicas/new
  def new
    @experiencia_agroecologica = ExperienciaAgroecologica.new
  end

  # GET /experiencia_agroecologicas/1/edit
  def edit
  end

  # POST /experiencia_agroecologicas
  # POST /experiencia_agroecologicas.json
  def create
    @experiencia_agroecologica = ExperienciaAgroecologica.new(experiencia_agroecologica_params)

    if ! current_usuario.admin?
      @experiencia_agroecologica.usuario_id = current_usuario.id
    end

    respond_to do |format|
      if @experiencia_agroecologica.save
        format.html { redirect_to @experiencia_agroecologica, notice: 'Experiência em Agroecologia foi cadastrada.' }
        format.json { render :show, status: :created, location: @experiencia_agroecologica }
      else
        format.html { render :new }
        format.json { render json: @experiencia_agroecologica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiencia_agroecologicas/1
  # PATCH/PUT /experiencia_agroecologicas/1.json
  def update
    respond_to do |format|
      if @experiencia_agroecologica.update(experiencia_agroecologica_params)
        format.html { redirect_to @experiencia_agroecologica, notice: 'Experiência em Agroecologia foi atualizada.' }
        format.json { render :show, status: :ok, location: @experiencia_agroecologica }
      else
        format.html { render :edit }
        format.json { render json: @experiencia_agroecologica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiencia_agroecologicas/1
  # DELETE /experiencia_agroecologicas/1.json
  def destroy
    @experiencia_agroecologica.destroy
    respond_to do |format|
      format.html { redirect_to experiencia_agroecologicas_url, notice: 'Experiência em Agroecologia foi removida.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiencia_agroecologica
      @experiencia_agroecologica = ExperienciaAgroecologica.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experiencia_agroecologica_params
      params.require(:experiencia_agroecologica).permit(:nome, :slug, :usuario_id, :local_id, :tema_experiencia_agroecologica_id, :resumo, :observacao)
    end

    def load_tema_experiencia_agroecologicas
      @tema_experiencia_agroecologicas = TemaExperienciaAgroecologica.all
    end

    def load_local
      if params[:local_id]
        @local = Local.friendly.find(params[:local_id])
      end
    end
end

app/views/experiencia_agroecologicas/_comentar.html.erb
<%= form_for([ @experiencia_agroecologica, comentar ], html: { multipart: true }) do |f| %>
  <div class="col-xs-4">
    <%= f.text_area :texto, rows: 5, class: "form-control" %>
    <br/>
    <%= f.submit t(:submit_comment), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/experiencia_agroecologicas/_comentarios.html.erb
  <div style="overflow-x:auto;">
    <table id="dataTable-agroecologia" class="table table-striped table-bordered" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th>Comentário</th>
          <th>Autor</th>
          <th>Data</th>
          <% if usuario_signed_in? %><th class="list-control"></th><% end %>
        </tr>
      </thead>

      <tbody>
        <% comentarios.each do |comentario| %>
        <tr>
          <td><%= comentario.texto %></td>
          <td><%= link_to comentario.usuario.nome, usuario_path(comentario.usuario) %></td>
          <td><%= comentario.created_at %></td>
          <% if usuario_signed_in? %>
            <% if current_usuario.admin? or comentario.usuario.id == current_usuario.id %>
              <td><%= link_to t(:destroy), comentario_path(comentario), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-sm btn-danger' %></td>
            <% else %>
              <td></td>
            <% end %>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <script>$(document).ready(function(){ dataTables(); });</script>

app/views/experiencia_agroecologicas/_form.html.erb
<%= form_for(experiencia_agroecologica, html: { multipart: true }) do |f| %>
  <% if experiencia_agroecologica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experiencia_agroecologica.errors.count, "error") %> encontrado(s):</h2>

      <ul>
      <% experiencia_agroecologica.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_usuario.admin? %>
    <div class="form-group row">
      <%= f.label 'Colaborador Responsável', class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <%= f.collection_select(:usuario_id, Usuario.all, :id, :nome,  {}, { class: "form-control selectpicker", "data-live-search": true } ) %>
      </div>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label 'Local', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <% if params[:local_id] %>
        <%= f.hidden_field :local_id, id: "local_id", :value => Local.friendly.find(params[:local_id]).id %>
        <%= params[:local_id] %>
      <% else %>
        <%= f.collection_select(:local_id, @locais, :id, :nome, {}, { class: "form-control selectpicker", "data-live-search": true } ) %>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Tema da Experiência', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.collection_select(:tema_experiencia_agroecologica_id, @tema_experiencia_agroecologicas, :id, :nome,  {}, { class: "form-control selectpicker", "data-live-search": true } ) %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Nome', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-5">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Resumo', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.text_area :resumo, class: "form-control", :rows => "12"  %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Observação', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.text_area :observacao, class: "form-control", :rows => "5"  %>
    </div>
  </div>

  <br/>
  <div class="actions">
    <%= f.submit t(:submit), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/experiencia_agroecologicas/edit.html.erb
<% title "Editando #{@experiencia_agroecologica.nome}" %>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "Experiências em Agroecologia", experiencia_agroecologicas_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{t(:edit)} #{@experiencia_agroecologica.nome}", edit_experiencia_agroecologica_path(@experiencia_agroecologica), :class => "nav-link active" %>
  </li>
</ul>
<br/>

<% if ! @locais.empty? %>
  <%= render 'form', experiencia_agroecologica: @experiencia_agroecologica %>
<% else %>
  <br/>
  <h3>Nenhum Local Cadastrado. Deseja <%= link_to "Cadastrar um Local Agora?", new_local_url %></h3>
<% end %>

app/views/experiencia_agroecologicas/index.html.erb
<% title 'Experiências em Agroecologia' %>

<%= link_to "Registrar Nova Experiência", new_experiencia_agroecologica_path, :class => "btn btn-primary", :style => "float:right;" %>
<br/><br/><br/>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "Experiências em Agroecologia #{ @local.blank? ? '' : '(' + @local.nome + ')' }", "#", :class => "nav-link active" %>
  </li>
</ul>

<% if @experiencia_agroecologicas.empty? %>
  <br/>
  <h3>Nenhuma Experiência em Agroecologia Registrada</h3>
<% else %>

  <br/>
  <div style="overflow-x:auto;">
    <table id="dataTable-agroecologia" class="table table-striped table-bordered" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th>Nome da Experiência</th>
          <th>Tema Central</th>
          <th>Local</th>
          <th>Fotos</th>
          <th>Comentários</th>
          <% if usuario_signed_in? %><th class="list-control"></th><th class="list-control"></th><% end %>
        </tr>
      </thead>

      <tbody>
        <% @experiencia_agroecologicas.each do |experiencia_agroecologica| %>
        <tr>
          <td><%= link_to truncate(experiencia_agroecologica.nome, length: 128), experiencia_agroecologica_path(experiencia_agroecologica) %></td>
          <td><%= experiencia_agroecologica.tema_experiencia_agroecologica.nome %></td>
          <td><%= link_to truncate(experiencia_agroecologica.local.nome, length: 128), local_path(experiencia_agroecologica.local) %></td>
          <td><%= link_to experiencia_agroecologica.midias.count, experiencia_agroecologica_midias_path(experiencia_agroecologica) %></td>
          <td><%= experiencia_agroecologica.comentarios.count %></td>

          <% if usuario_signed_in? %>
            <% if current_usuario.admin? or experiencia_agroecologica.usuario.id == current_usuario.id %>
              <td><%= link_to t(:edit), edit_experiencia_agroecologica_path(experiencia_agroecologica), :class => 'btn btn-sm btn-success' %></td>
              <td><%= link_to t(:destroy), experiencia_agroecologica_path(experiencia_agroecologica), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-sm btn-danger' %></td>
            <% else %>
              <td></td><td></td>
            <% end %>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <script>$(document).ready(function(){ dataTables(); });</script>
<% end %>

app/views/experiencia_agroecologicas/new.html.erb
<% title "Adicionar Experiência em Agroecologia" %>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "Experiências em Agroecologia", experiencia_agroecologicas_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:new), new_experiencia_agroecologica_path, :class => "nav-link active" %>
  </li>
</ul>

<br/>

<% if ! @locais.empty? %>
  <%= render 'form', experiencia_agroecologica: @experiencia_agroecologica %>
<% else %>
  <br/>
  <h3>Nenhum Local Cadastrado. Deseja <%= link_to "Cadastrar um Local Agora?", new_local_url %></h3>
<% end %>

app/views/experiencia_agroecologicas/show.html.erb
<% title @experiencia_agroecologica.nome %>

<%= link_to "Registrar Nova Experiência", new_experiencia_agroecologica_path, :class => "btn btn-primary", :style => "float:right;" %>
<br/><br/><br/>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "Experiências em Agroecologia", experiencia_agroecologicas_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to @experiencia_agroecologica.nome, experiencia_agroecologica_path(@experiencia_agroecologica.id), :class => "nav-link active" %>
  </li>
  <li class="nav-item">
    <%= link_to "Fotos (#{@experiencia_agroecologica.midias.count})", experiencia_agroecologica_midias_path(@experiencia_agroecologica), :class => "nav-link" %>
  </li>
</ul>

<br/>

<div class="tab-content" style="min-height: 64px;">
  <div class="tab-pane active">
    <center>
      <br/><br/>
      <h3><%= @experiencia_agroecologica.nome %></h3>

      <br/>
      <%= "<strong>Tema:</strong><br/>#{@experiencia_agroecologica.tema_experiencia_agroecologica.nome}&nbsp;".html_safe if @experiencia_agroecologica.tema_experiencia_agroecologica.nome?%>
      <%= "<br/><br/><strong>Resumo:</strong><br/>#{@experiencia_agroecologica.resumo}&nbsp;".html_safe if @experiencia_agroecologica.resumo?%>
      <%= "<br/><br/><strong>Local:</strong><br/>#{link_to @experiencia_agroecologica.local.nome, local_path(@experiencia_agroecologica.local)}&nbsp;".html_safe if @experiencia_agroecologica.local.nome?%>
      <%= "<br/><br/><strong>Responsável pela Informação:</strong><br/>#{link_to @experiencia_agroecologica.usuario.nome, usuario_path(@experiencia_agroecologica.usuario)}&nbsp;".html_safe if @experiencia_agroecologica.usuario.nome?%>
      <%= "<br/><br/><strong>Organização:</strong><br/>#{@experiencia_agroecologica.local.organizacoes.map {|organizacao| link_to organizacao.nome, organizacao_path(organizacao)}.join(", ").html_safe}&nbsp;".html_safe if @experiencia_agroecologica.local.organizacoes.count > 0%>
      <%= "<br/><br/><strong>Observação:</strong><br/>#{@experiencia_agroecologica.observacao}&nbsp;".html_safe if @experiencia_agroecologica.observacao?%>

      <br/><br/><strong>Comentários:</strong><br/>
      <% if @experiencia_agroecologica.comentarios.count > 0 %>
        <%= render 'comentarios', comentarios: @experiencia_agroecologica.comentarios %>
      <% end %>

      <%= "<b>#{link_to 'Logue no sistema para fazer comentários', new_usuario_session_path, :class => 'text-danger'}</b>".html_safe if ! usuario_signed_in? %>

      <br/></br>     

      <%= render 'comentar', comentar: @comentar if usuario_signed_in? %>

    </center>
  </div>
</div>

<% if usuario_signed_in? %>
  <% if current_usuario.admin? or current_usuario.id == @experiencia_agroecologica.usuario.id %>        
    <br/><br/>
    <div id="experiencia_agroecologica-footer">
      <div class="form-actions">
        <%= link_to t('.edit', :default => "Editar"), edit_experiencia_agroecologica_path(@experiencia_agroecologica), :class => 'btn btn-success' %>
        <%= link_to "Enviar Foto para esta Experiência", new_experiencia_agroecologica_midia_path(@experiencia_agroecologica), :class => "btn btn-warning" %>
        <%= link_to t(:destroy), experiencia_agroecologica_path(@experiencia_agroecologica), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-danger' %>
      </div>
    </div>
  <% end %>
<% end %>