config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /pt-BR|es|en/ do
    root :to => "home#index"
    get "home/index"
  end

  resources :comentarios
  resources :animais
  resources :plantas

  resources :experiencia_agroecologicas do
    resources :midias
    resources :comentarios
  end

  resources :safs do
    resources :midias
  end

  resources :tema_experiencia_agroecologicas

  resources :locais do
    resources :experiencia_agroecologicas
    resources :safs 
    resources :blogs, :path => "blog"
  end

  resources :organizacoes

  resources :tipo_organizacoes

  devise_for :usuarios

  resources :usuarios do
    resources :locais
  end

  resources :novidades, :only => [:index]
end

app/models/saf.rb
class Saf < ApplicationRecord
  belongs_to :local
  belongs_to :usuario
  has_one :organizacao, through: :local
  has_many :midias, :dependent => :delete_all

  has_many :saf_plantas, dependent: :destroy
  has_many :plantas, through: :saf_plantas
  accepts_nested_attributes_for :saf_plantas, allow_destroy: true

  has_many :saf_animais, dependent: :destroy
  has_many :animais, through: :saf_animais
  accepts_nested_attributes_for :saf_animais, allow_destroy: true

  extend FriendlyId
  friendly_id :nome, use: :slugged

  validates :nome, presence: true, uniqueness: true
  validates :local, presence: true

  protected
    def should_generate_new_friendly_id?
      nome_changed?
    end
end

app/controllers/safs_controller.rb
class SafsController < ApplicationController
  before_action :set_saf, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, only: [:new, :edit, :update, :destroy]
  before_action -> { check_owner Saf.friendly.find(params[:id]).usuario_id }, only: [:edit, :update, :destroy]
  before_action :load_locais, except: [:index, :show]
  before_action :load_plantas_animais, except: [:index]
  before_action :load_local

  # GET /safs
  # GET /safs.json
  def index
    if params[:local_id]
      @safs = Saf.where(:local_id => @local.id).sort_by(&:updated_at).reverse
    else
      @safs = Saf.all.sort_by(&:updated_at).reverse
    end
  end

  # GET /safs/1
  # GET /safs/1.json
  def show
  end

  # GET /safs/new
  def new
    @saf = Saf.new
    @saf.saf_plantas.build
    @saf.saf_animais.build
  end

  # GET /safs/1/edit
  def edit
    @saf.saf_plantas.build
    @saf.saf_animais.build
  end

  # POST /safs
  # POST /safs.json
  def create
    @saf = Saf.new(saf_params)

    if ! current_usuario.admin?
      @saf.usuario_id = current_usuario.id
    end

    respond_to do |format|
      if @saf.save
        format.html { redirect_to @saf, notice: 'SAF foi cadastrado.' }
        format.json { render :show, status: :created, location: @saf }
      else
        format.html { render :new }
        format.json { render json: @saf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /safs/1
  # PATCH/PUT /safs/1.json
  def update
    respond_to do |format|
      if @saf.update(saf_params)
        format.html { redirect_to @saf, notice: 'SAF foi atualizado.' }
        format.json { render :show, status: :ok, location: @saf }
      else
        format.html { render :edit }
        format.json { render json: @saf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /safs/1
  # DELETE /safs/1.json
  def destroy
    @saf.destroy
    respond_to do |format|
      format.html { redirect_to safs_url, notice: 'SAF foi removido.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saf
      @saf = Saf.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saf_params
      params.require(:saf).permit(:nome, :slug, :objetivo, :produto_principal, :inicio, :fim, :area, :local_id, :usuario_id, :observacao, planta_ids: [], animal_ids: [])
    end

    def load_plantas_animais
      @plantas = Planta.all
      @animais = Animal.all
    end

    def load_local
      if params[:local_id]
        @local = Local.friendly.find(params[:local_id])
      end
    end
end

app/views/safs/_form.html.erb
<%= form_for(saf, html: { multipart: true }) do |f| %>
  <% if saf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(saf.errors.count, "error") %> encontrado(s):</h2>

      <ul>
      <% saf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_usuario.admin? %>
    <div class="form-group row">
      <%= f.label 'Colaborador Responsável', class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <%= f.collection_select(:usuario_id, Usuario.all, :id, :nome,  {}, { class: "form-control selectpicker", "data-live-search": true } ) %>
      </div>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label 'Local', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <% if params[:local_id] %>
        <%= f.hidden_field :local_id, id: "local_id", :value => Local.friendly.find(params[:local_id]).id %>
        <%= params[:local_id] %>
      <% else %>
        <%= f.collection_select(:local_id, @locais, :id, :nome, {}, { class: "form-control selectpicker", "data-live-search": true } ) %>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Nome', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-5">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Objetivo Principal', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.text_field :objetivo, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Produto Principal', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.text_field :produto_principal, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Data de Início', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-5">
      <%= f.date_field :inicio, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Data de Fim (Opcional)', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-5">
      <%= f.date_field :fim, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Área (ha)', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-2">
      <%= f.text_field :area, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Plantas Associadas', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <% if ! @plantas.empty? %>
        <%= f.collection_select(:planta_ids, @plantas, :id, :nome,  { include_hidden: true }, { class: "form-control selectpicker show-tick", multiple: true, "data-live-search": true } ) %>
      <% else %>
        <b>Não há Plantas Registradas. Deseja <%= link_to "Cadastrar?", new_planta_path, :target => "blank"%></b>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Animais Associados', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <% if ! @animais.empty? %>
        <%= f.collection_select(:animal_ids, @animais, :id, :nome,  { include_hidden: true }, { class: "form-control selectpicker show-tick", multiple: true, "data-live-search": true } ) %>
      <% else %>
        <b>Não há Animais Registrados. Deseja <%= link_to "Cadastrar?", new_animal_path, :target => "blank"%></b>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label 'Observação', class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-10">
      <%= f.text_area :observacao, class: "form-control", :rows => "5"  %>
    </div>
  </div>

  <br/>
  <div class="actions">
    <%= f.submit t(:submit), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/safs/edit.html.erb
<% title "Editando #{@saf.nome}" %>

<ul class="nav nav-tabs">
  <% if usuario_signed_in? %>
    <li class="nav-item">
      <%= link_to "SAFs", safs_path, :class => "nav-link" %>
    </li>
  <% end %>
  <li class="nav-item">
    <%= link_to "#{t(:edit)} #{@saf.nome}", edit_saf_path(@saf), :class => "nav-link active" %>
  </li>
</ul>
<br/>

<% if ! @locais.empty? %>
  <%= render 'form', saf: @saf %>
<% else %>
  <br/>
  <h3>Nenhum Local Cadastrado. Deseja <%= link_to "Cadastrar um Local Agora?", new_local_url %></h3>
<% end %>

app/views/safs/index.html.erb
<% title 'Sistemas Agroflorestais' %>

<%= link_to "Registrar Novo SAF", new_saf_path, :class => "btn btn-primary", :style => "float:right;" %>
<br/><br/><br/>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "SAFs #{ @local.blank? ? '' : '(' + @local.nome + ')' }", "#", :class => "nav-link active" %>
  </li>
</ul>

<% if @safs.empty? %>
  <br/>
  <h3>Nenhum SAF Registrado</h3>
<% else %>

  <br/>
  <div style="overflow-x:auto;">
    <table id="dataTable-agroecologia" class="table table-striped table-bordered" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th>Nome da SAF</th>
          <th>Local</th>
          <th>Fotos</th>
          <th>Plantas</th>
          <th>Animais</th>
          <% if usuario_signed_in? %><th class="list-control"></th><th class="list-control"></th><% end %>
        </tr>
      </thead>

      <tbody>
        <% @safs.each do |saf| %>
        <tr>
          <td><%= link_to saf.nome, saf_path(saf) %></td>
          <td><%= link_to saf.local.nome, local_path(saf.local) %></td>
          <td><%= link_to saf.midias.count, saf_midias_path(saf) %></td>
          <td><%= saf.plantas.count %></td>
          <td><%= saf.animais.count %></td>
          <% if usuario_signed_in? %>
            <% if current_usuario.admin? or saf.usuario.id == current_usuario.id %>
              <td><%= link_to t(:edit), edit_saf_path(saf), :class => 'btn btn-sm btn-success' %></td>
              <td><%= link_to t(:destroy), saf_path(saf), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-sm btn-danger' %></td>
            <% else %>
              <td></td><td></td>
            <% end %>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <script>$(document).ready(function(){ dataTables(); });</script>
<% end %>

app/views/safs/new.html.erb
<% title "Adicionar Sistema Agroflorestal" %>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "SAFs", safs_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:new), new_saf_path, :class => "nav-link active" %>
  </li>
</ul>
<br/>
<% if ! @locais.empty? %>
  <%= render 'form', saf: @saf %>
<% else %>
  <br/>
  <h3>Nenhum Local Cadastrado. Deseja <%= link_to "Cadastrar um Local Agora?", new_local_url %></h3>
<% end %>

app/views/safs/show.html.erb
<% title @saf.nome %>

<%= link_to "Registrar Novo SAF", new_saf_path, :class => "btn btn-primary", :style => "float:right;" %>
<br/><br/><br/>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "SAFs", safs_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to @saf.nome, saf_path(@saf.id), :class => "nav-link active" %>
  </li>
  <li class="nav-item">
    <%= link_to "Fotos (#{@saf.midias.count})", saf_midias_path(@saf), :class => "nav-link" %>
  </li>
</ul>

<br/>

<div class="tab-content" style="min-height: 64px;">
  <div class="tab-pane active">
    <center>
      <br/><br/>
      <h3><%= @saf.nome %></h3>

      <br/>
      <%= "<strong>Local:</strong><br/>#{link_to @saf.local.nome, local_path(@saf.local)}&nbsp;".html_safe if @saf.local.nome?%>
      <%= "<br/><br/><strong>Objetivo Principal:</strong><br/>#{@saf.objetivo}&nbsp;".html_safe if @saf.objetivo?%>
      <%= "<br/><br/><strong>Produto Principal:</strong><br/>#{@saf.produto_principal}&nbsp;".html_safe if @saf.produto_principal?%>
      <%= "<br/><br/><strong>Início:</strong><br/>#{@saf.inicio}&nbsp;".html_safe if @saf.inicio?%>
      <%= "<br/><br/><strong>Fim:</strong><br/>#{@saf.fim}&nbsp;".html_safe if @saf.fim?%>
      <%= "<br/><br/><strong>Área (ha):</strong><br/>#{@saf.area}&nbsp;".html_safe if @saf.area?%>
      <%= "<br/><br/><strong>Responsável pela Informação:</strong><br/>#{link_to @saf.usuario.nome, usuario_path(@saf.usuario)}&nbsp;".html_safe if @saf.usuario.nome?%>
      <%= "<br/><br/><strong>Organização:</strong><br/>#{@saf.local.organizacoes.map {|organizacao| link_to organizacao.nome, organizacao_path(organizacao)}.join(", ").html_safe}&nbsp;".html_safe if @saf.local.organizacoes.count > 0%>
      <%= "<br/><br/><strong>Plantas:</strong><br/>#{@saf.plantas.map {|planta| link_to planta.nome, planta_path(planta)}.join(", ").html_safe}&nbsp;".html_safe if @saf.plantas.count > 0%>
      <%= "<br/><br/><strong>Animais:</strong><br/>#{@saf.animais.map {|animal| link_to animal.nome, animal_path(animal)}.join(", ").html_safe}&nbsp;".html_safe if @saf.animais.count > 0%>
      <%= "<br/><br/><strong>Observação:</strong><br/>#{@saf.observacao}&nbsp;".html_safe if @saf.observacao?%>

    </center>
  </div>
</div>

<% if usuario_signed_in? %>
  <% if current_usuario.admin? or current_usuario.id == @saf.usuario.id %>        
    <br/><br/>
    <div id="saf-footer">
      <div class="form-actions">
        <%= link_to t('.edit', :default => "Editar"), edit_saf_path(@saf), :class => 'btn btn-success' %>
        <%= link_to "Enviar Foto para esta SAF", new_saf_midia_path(@saf), :class => "btn btn-warning" %>
        <%= link_to t(:destroy), saf_path(@saf), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-danger' %>
      </div>
    </div>
  <% end %>
<% end %>